In [1]:
import numpy as np
import time
import matplotlib.pyplot as plt
import sys

sys.path.insert(0, 'dummydirectory') #'/content/drive/My Drive/Colab Notebooks/gamenight'

from arena import letsplay 
from scoring import score_stich, score_game, did_cheat

from group0 import play as player0
from group1 import play as player1
from group2 import play as player2
from group3 import play as player3

players = [player0, player1, player2, player3]

In [2]:
ncards = 10
toprint = False
score, history = letsplay(players,ncards,toprint,score_stich,score_game,did_cheat);

[0 1 2 3]
[[-1 -1 -1 -1]]
[[ 3 -1 -1 -1]]
[[ 3  0 -1 -1]]
[[ 3  0  9 -1]]

[[3 0 9 0]]
[2 3 0 1]
[[ 3  0  9  0]
 [-1 -1 -1 -1]]
[[ 3  0  9  0]
 [-1 -1  8 -1]]
[[ 3  0  9  0]
 [-1 -1  8  1]]
[[ 3  0  9  0]
 [ 8 -1  8  1]]

[[3 0 9 0]
 [8 9 8 1]]
[1 2 3 0]
[[ 3  0  9  0]
 [ 8  9  8  1]
 [-1 -1 -1 -1]]
[[ 3  0  9  0]
 [ 8  9  8  1]
 [-1  4 -1 -1]]
[[ 3  0  9  0]
 [ 8  9  8  1]
 [-1  4  7 -1]]
[[ 3  0  9  0]
 [ 8  9  8  1]
 [-1  4  7  2]]

[[3 0 9 0]
 [8 9 8 1]
 [0 4 7 2]]
[2 3 0 1]
[[ 3  0  9  0]
 [ 8  9  8  1]
 [ 0  4  7  2]
 [-1 -1 -1 -1]]
[[ 3  0  9  0]
 [ 8  9  8  1]
 [ 0  4  7  2]
 [-1 -1  6 -1]]
[[ 3  0  9  0]
 [ 8  9  8  1]
 [ 0  4  7  2]
 [-1 -1  6  3]]
[[ 3  0  9  0]
 [ 8  9  8  1]
 [ 0  4  7  2]
 [ 6 -1  6  3]]

[[3 0 9 0]
 [8 9 8 1]
 [0 4 7 2]
 [6 7 6 3]]
[1 2 3 0]
[[ 3  0  9  0]
 [ 8  9  8  1]
 [ 0  4  7  2]
 [ 6  7  6  3]
 [-1 -1 -1 -1]]
[[ 3  0  9  0]
 [ 8  9  8  1]
 [ 0  4  7  2]
 [ 6  7  6  3]
 [-1  3 -1 -1]]
[[ 3  0  9  0]
 [ 8  9  8  1]
 [ 0  4  7  2]
 [ 6  7  6  3]
 [-1

In [3]:
score

array([0, 2, 0, 2])

In [4]:
history

array([[3, 0, 9, 0],
       [8, 9, 8, 1],
       [0, 4, 7, 2],
       [6, 7, 6, 3],
       [9, 3, 5, 4],
       [2, 8, 4, 5],
       [4, 6, 3, 6],
       [1, 8, 2, 7],
       [7, 8, 1, 8],
       [5, 0, 0, 9]])

In [5]:
did_cheat(history)

array([False,  True, False, False])