In [1]:
import numpy as np
import time
import matplotlib.pyplot as plt
import sys

#sys.path.insert(0, '/content/drive/My Drive/Colab Notebooks/gamenight')      ## <<<<< for Google Colab
sys.path.insert(0, 'dummydirectory')

from arena import letsplay 
from scoring import score_stich, score_game, did_cheat

from group0 import play as player0
from group1 import play as player1

players = [player0,player0,player1,player1]

In [2]:
ncards = 10
toprint = False
score, history = letsplay(players,ncards,toprint,score_stich,score_game,did_cheat);

[0 1 2 3]
[[0 0 0 0]]
[[4 0 0 0]]
[[4 2 0 0]]
[[4 2 3 0]]

[[4 2 3 8]]
[0 1 2 3]
[[4 2 3 8]
 [0 0 0 0]]
[[4 2 3 8]
 [1 0 0 0]]
[[4 2 3 8]
 [1 1 0 0]]
[[4 2 3 8]
 [1 1 5 0]]

[[4 2 3 8]
 [1 1 5 2]]
[3 0 1 2]
[[4 2 3 8]
 [1 1 5 2]
 [0 0 0 0]]
[[4 2 3 8]
 [1 1 5 2]
 [0 0 0 6]]
[[4 2 3 8]
 [1 1 5 2]
 [5 0 0 6]]
[[4 2 3 8]
 [1 1 5 2]
 [5 0 0 6]]

[[4 2 3 8]
 [1 1 5 2]
 [5 0 5 6]]
[0 1 2 3]
[[4 2 3 8]
 [1 1 5 2]
 [5 0 5 6]
 [0 0 0 0]]
[[4 2 3 8]
 [1 1 5 2]
 [5 0 5 6]
 [3 0 0 0]]
[[4 2 3 8]
 [1 1 5 2]
 [5 0 5 6]
 [3 7 0 0]]
[[4 2 3 8]
 [1 1 5 2]
 [5 0 5 6]
 [3 7 2 0]]

[[4 2 3 8]
 [1 1 5 2]
 [5 0 5 6]
 [3 7 2 6]]
[3 0 1 2]
[[4 2 3 8]
 [1 1 5 2]
 [5 0 5 6]
 [3 7 2 6]
 [0 0 0 0]]
[[4 2 3 8]
 [1 1 5 2]
 [5 0 5 6]
 [3 7 2 6]
 [0 0 0 1]]
[[4 2 3 8]
 [1 1 5 2]
 [5 0 5 6]
 [3 7 2 6]
 [7 0 0 1]]
[[4 2 3 8]
 [1 1 5 2]
 [5 0 5 6]
 [3 7 2 6]
 [7 6 0 1]]

[[4 2 3 8]
 [1 1 5 2]
 [5 0 5 6]
 [3 7 2 6]
 [7 6 6 1]]
[0 1 2 3]
[[4 2 3 8]
 [1 1 5 2]
 [5 0 5 6]
 [3 7 2 6]
 [7 6 6 1]
 [0 0 0 0]]
[[4 2 3 8]
 [1 1 5

In [3]:
score

array([2, 2, 0, 0])

In [4]:
history

array([[4, 2, 3, 8],
       [1, 1, 5, 2],
       [5, 0, 5, 6],
       [3, 7, 2, 6],
       [7, 6, 6, 1],
       [6, 9, 7, 6],
       [8, 8, 6, 7],
       [2, 5, 7, 1],
       [9, 3, 7, 1],
       [0, 4, 7, 0]])

In [5]:
did_cheat(history)

array([False, False,  True,  True])